[Calibration.Configuration]
	"Folds" = 5
	"Stratification Groups" = 5
	"Seed" = 72
	"Scalers" = "All"

[Calibration.Techniques.Default]
	"Linear Regression" = true
	"Ridge Regression" = true
	"Ridge Regression (Cross Validated)" = true
	"Lasso Regression" = true
	"Lasso Regression (Cross Validated)" = true
	"Elastic Net Regression" = true
	"Elastic Net Regression (Cross Validated)" = true
	"Least Angle Regression" = true
	"Least Angle Lasso Regression" = true
	"Orthogonal Matching Pursuit" = true
	"Bayesian Ridge Regression" = true
	"Bayesian Automatic Relevance Detection" = true
	"Tweedie Regression" = true
	"Stochastic Gradient Descent" = true
	"Passive Aggressive Regression" = true
	"RANSAC" = true
	"Theil-Sen Regression" = true
	"Huber Regression" = true
	"Quantile Regression" = true
	"Decision Tree" = true
	"Extra Tree" = true
	"Random Forest" = false
	"Extra Trees Ensemble" = false
	"Gradient Boosting Regression" = true
	"Histogram-Based Gradient Boosting Regression" = true
	"Multi-Layer Perceptron Regression" = true
	"Support Vector Regression" = true
	"Linear Support Vector Regression" = true
	"Nu-Support Vector Regression" = true
	"Gaussian Process Regression" = false
	"Isotonic Regression" = true
	"XGBoost Regression" = true
	"XGBoost Random Forest Regression" = true	
	"Linear GAM" = true
	"Expectile GAM" = true

[Calibration.Techniques."Random Search"]
	"Linear Regression" = false
	"Ridge Regression" = false
	"Lasso Regression" = false
	"Elastic Net Regression" = false
	"Least Angle Regression" = false
	"Least Angle Lasso Regression" = false
	"Orthogonal Matching Pursuit" = false
	"Bayesian Ridge Regression" = false
	"Bayesian Automatic Relevance Detection" = false
	"Tweedie Regression" = false
	"Stochastic Gradient Descent" = false
	"Passive Aggressive Regression" = false
	"RANSAC" = false
	"Theil-Sen Regression" = false
	"Huber Regression" = false
	"Quantile Regression" = false
	"Decision Tree" = false
	"Extra Tree" = false
	"Random Forest" = false
	"Extra Trees Ensemble" = false
	"Gradient Boosting Regression" = false
	"Histogram-Based Gradient Boosting Regression" = false
	"Multi-Layer Perceptron Regression" = false
	"Support Vector Regression" = false
	"Linear Support Vector Regression" = false
	"Nu-Support Vector Regression" = false
	"Gaussian Process Regression" = false
	"Isotonic Regression" = false
	"XGBoost Regression" = false
	"XGBoost Random Forest Regression" = false	

[Calibration."Secondary Variables"]
	"PM1" = ["RH", "T"]
	"PM2.5" = ["RH", "T"]
	"PM4" = ["RH", "T"]
	"PM10" = ["RH", "T"]
	"NO" = ["RH", "T", "NO2", "O3"]
	"NO2" = ["RH", "T", "NO", "O3"]
	"O3" = ["RH", "T", "NO", "NO2"]

[Metrics]
	"Explained Variance Score" = false
	"Max Error" = true
	"Mean Absolute Error" = true
	"Root Mean Squared Error" = true
	"Root Mean Squared Log Error" = false
	"Median Absolute Error" = true
	"Mean Absolute Percentage Error" = true
	"r2" = true
	"Mean Poisson Deviance" = false
	"Mean Gamma Deviance" = false
	"Mean Tweedie Deviance" = false
	"Mean Pinball Loss" = true
	"Centered Root Mean Squared Error" = true
	"Unnbiased Root Mean Squared Error" = true
	"Mean Bias Error" = true
	"Reference IQR" = true
	"Reference Mean" = true
	"Reference Range" = true
	"Reference Standard Deviation" = true

[Comparisons."Cranfield"]
	"Start" = 2022-01-01
	"End" = 2023-09-01
	"Averaging Operator" = "mean"
	"Averaging Period" = "1h"

[Comparisons."Cranfield".Devices."Reference"]
	"Bucket" = "Cranfield"
	"Measurement" = "Reference"
	"Use as Reference" = true

[[Comparisons."Cranfield".Devices."Reference".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Pm2.5"

[[Comparisons."Cranfield".Devices."Reference".Fields]]
	"Tag" = "PM10"
	"Field" = "Pm10"

[[Comparisons."Cranfield".Devices."Reference".Fields]]
	"Tag" = "NO2"
	"Field" = "NitrogenDioxide"

[[Comparisons."Cranfield".Devices."Reference".Fields]]
	"Tag" = "O3"
	"Field" = "Ozone"

[Comparisons."Cranfield".Devices."Zep_1107b"]
	"Bucket" = "Cranfield"
	"Measurement" = "Zephyr"
	"Boolean Filters"."Platform" = "Zep_1107b"
	"Use as Reference" = false

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Particulatepm25"

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "PM10"
	"Field" = "Particulatepm10"

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "NO"
	"Field" = "No"

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "NO2"
	"Field" = "No2"

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "O3"
	"Field" = "O3"

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "RH"
	"Field" = "Humidity"

[[Comparisons."Cranfield".Devices."Zep_1107b".Fields]]
	"Tag" = "T"
	"Field" = "Tempc"

[Comparisons."Cranfield".Devices."Zep_753"]
	"Bucket" = "Cranfield"
	"Measurement" = "Zephyr"
	"Boolean Filters"."Platform" = "Zep_753"
	"Use as Reference" = false

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Particulatepm25"

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "PM10"
	"Field" = "Particulatepm10"

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "NO"
	"Field" = "No"

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "NO2"
	"Field" = "No2"

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "O3"
	"Field" = "O3"

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "RH"
	"Field" = "Humidity"

[[Comparisons."Cranfield".Devices."Zep_753".Fields]]
	"Tag" = "T"
	"Field" = "Tempc"

[Comparisons."Cranfield".Devices."Zep_754"]
	"Bucket" = "Cranfield"
	"Measurement" = "Zephyr"
	"Boolean Filters"."Platform" = "Zep_754"
	"Use as Reference" = false

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Particulatepm25"

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "PM10"
	"Field" = "Particulatepm10"

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "NO"
	"Field" = "No"

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "NO2"
	"Field" = "No2"

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "O3"
	"Field" = "O3"

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "RH"
	"Field" = "Humidity"

[[Comparisons."Cranfield".Devices."Zep_754".Fields]]
	"Tag" = "T"
	"Field" = "Tempc"

[Comparisons."Cranfield".Devices."Zep_757"]
	"Bucket" = "Cranfield"
	"Measurement" = "Zephyr"
	"Boolean Filters"."Platform" = "Zep_757"
	"Use as Reference" = false

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Particulatepm25"

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "PM10"
	"Field" = "Particulatepm10"

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "NO"
	"Field" = "No"

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "NO2"
	"Field" = "No2"

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "O3"
	"Field" = "O3"

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "RH"
	"Field" = "Humidity"

[[Comparisons."Cranfield".Devices."Zep_757".Fields]]
	"Tag" = "T"
	"Field" = "Tempc"

[Comparisons."Cranfield".Devices."Zep_858"]
	"Bucket" = "Cranfield"
	"Measurement" = "Zephyr"
	"Boolean Filters"."Platform" = "Zep_858"
	"Use as Reference" = false

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Particulatepm25"

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "PM10"
	"Field" = "Particulatepm10"

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "NO"
	"Field" = "No"

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "NO2"
	"Field" = "No2"

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "O3"
	"Field" = "O3"

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "RH"
	"Field" = "Humidity"

[[Comparisons."Cranfield".Devices."Zep_858".Fields]]
	"Tag" = "T"
	"Field" = "Tempc"
