[Calibration.Configuration]
	"Folds" = 5
	"Stratification Groups" = 10
	"Seed" = 72
	"Scalers" = "All"

[Calibration.Techniques.Default]
	"Linear Regression" = true
	"Ridge Regression" = true
	"Ridge Regression (Cross Validated)" = true
	"Lasso Regression" = true
	"Lasso Regression (Cross Validated)" = true
	"Elastic Net Regression" = true
	"Elastic Net Regression (Cross Validated)" = true
	"Least Angle Regression" = true
	"Least Angle Lasso Regression" = true
	"Orthogonal Matching Pursuit" = true
	"Bayesian Ridge Regression" = true
	"Bayesian Automatic Relevance Detection" = true
	"Tweedie Regression" = true
	"Stochastic Gradient Descent" = true
	"Passive Aggressive Regression" = true
	"RANSAC" = true
	"Theil-Sen Regression" = true
	"Huber Regression" = true
	"Quantile Regression" = true
	"Decision Tree" = true
	"Extra Tree" = true
	"Random Forest" = false
	"Extra Trees Ensemble" = false
	"Gradient Boosting Regression" = true
	"Histogram-Based Gradient Boosting Regression" = true
	"Multi-Layer Perceptron Regression" = true
	"Support Vector Regression" = true
	"Linear Support Vector Regression" = true
	"Nu-Support Vector Regression" = true
	"Gaussian Process Regression" = false
	"Isotonic Regression" = true
	"XGBoost Regression" = true
	"XGBoost Random Forest Regression" = true	

[Calibration.Techniques."Random Search"]
	"Linear Regression" = false
	"Ridge Regression" = false
	"Lasso Regression" = false
	"Elastic Net Regression" = false
	"Least Angle Regression" = false
	"Least Angle Lasso Regression" = false
	"Orthogonal Matching Pursuit" = false
	"Bayesian Ridge Regression" = false
	"Bayesian Automatic Relevance Detection" = false
	"Tweedie Regression" = false
	"Stochastic Gradient Descent" = false
	"Passive Aggressive Regression" = false
	"RANSAC" = false
	"Theil-Sen Regression" = false
	"Huber Regression" = false
	"Quantile Regression" = false
	"Decision Tree" = false
	"Extra Tree" = false
	"Random Forest" = false
	"Extra Trees Ensemble" = false
	"Gradient Boosting Regression" = false
	"Histogram-Based Gradient Boosting Regression" = false
	"Multi-Layer Perceptron Regression" = false
	"Support Vector Regression" = false
	"Linear Support Vector Regression" = false
	"Nu-Support Vector Regression" = false
	"Gaussian Process Regression" = false
	"Isotonic Regression" = false
	"XGBoost Regression" = false
	"XGBoost Random Forest Regression" = false	

[Calibration."Secondary Variables"]
	"PM1" = ["RH", "T"]
	"PM2.5" = ["RH", "T"]
	"PM4" = ["RH", "T"]
	"PM10" = ["RH", "T"]
	"NO" = ["RH", "T", "NO2", "O3"]
	"NO2" = ["RH", "T", "NO", "O3"]
	"O3" = ["RH", "T", "NO", "NO2"]

[Calibration.Errors]
	"Explained Variance Score" = true
	"Max Error" = true
	"Mean Absolute Error" = true
	"Root Mean Squared Error" = true
	"Root Mean Squared Log Error" = false
	"Median Absolute Error" = true
	"Mean Absolute Percentage Error" = true
	"r2" = true
	"Mean Poisson Deviance" = false
	"Mean Gamma Deviance" = false
	"Mean Tweedie Deviance" = false
	"Mean Pinball Loss" = true



[Comparisons.""]
	"Start" = 2018-01-01
	"End" = 2022-01-01
	"Averaging Operator" = "mean"

[Comparisons."Bushy Park".Devices."NPL AQMesh A"]
	"Bucket" = "ACOEM Data"
	"Measurement" = "ACOEM UK Systems"
	"Boolean Filters"."SerialNumber" = "1505150"
	"Hour Beginning" = false

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "PM1"
	"Field" = "Particulate Matter (PM 1) PreScaled [Micrograms Per Cubic Meter]"
	"Boolean Filters"."Particulate Matter (PM 1) Flag" = "Valid"

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "PM2.5"
	"Field" = "Particulate Matter (PM 2.5) PreScaled [Micrograms Per Cubic Meter]"
	"Boolean Filters"."Particulate Matter (PM 2.5) Flag" = "Valid"

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "PM4"
	"Field" = "PM 4 PreScaled [Micrograms Per Cubic Meter]"
	"Boolean Filters"."PM 4 Flag" = "Valid"

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "PM10"
	"Field" = "Particulate Matter (PM 10) PreScaled [Micrograms Per Cubic Meter]"
	"Boolean Filters"."Particulate Matter (PM 10) Flag" = "Valid"

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "NO"
	"Field" = "Nitric Oxide PreScaled [Parts Per Billion]"
	"Boolean Filters"."Nitric Oxide Flag" = "Valid"
	"Scaling" = [
		{"Slope" = 1.25}
	]

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "NO2"
	"Field" = "Nitrogen Dioxide PreScaled [Parts Per Billion]"
	"Boolean Filters"."Nitrogen Dioxide Flag" = "Valid"
	"Scaling" = [
		{"Slope" = 1.88}
	]

[[Comparisons."Bushy Park".Devices."NPL AQMesh A".Fields]]
	"Tag" = "O3"
	"Field" = "Ozone PreScaled [Parts Per Billion]"
	"Boolean Filters"."Ozone Flag" = "Valid"
	"Scaling" = [
		{"Slope" = 2}
	]

[[Comparisons."Bushy Park".Devices."NPL AQMesh A"."Secondary Fields"]]
	"Tag" = "RH"
	"Field" = "Humidity PreScaled [Percent]"

[[Comparisons."Bushy Park".Devices."NPL AQMesh A"."Secondary Fields"]]
	"Tag" = "T"
	"Field" = "Temperature PreScaled [Celsius]"
